wip: feature function #25 - adapting to most recent FnO spec
FunctionLoader
- handling the function loader as a singleton → avoids unnecessary parsing of the function description graph

StdFunctionLoader
- parses the functions according to the new FnO spec (i.e. no more "lib:provided-by" things etc..)
- Dedicated FnO exceptions are thrown when needed

RMLVoc
- fno namespace changed from http → https
- added fnoi, fnom and doap namespaces

FunctionGeneratorAssembler
- now uses the singleton functionloader to load the function

FunctionUtils:
- added more type classes

FnOException: new exception class for when things regarding fno go wrong